# Generated by Django 3.2.13 on 2022-11-10 06:09


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="followings",
            new_name="followings",
        ),
    ]
