# Generated by Django 3.2.13 on 2022-11-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_tagmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
            preserve_default=False,
        ),
    ]
