# Generated by Django 3.2.13 on 2022-11-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_image_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='review_image',
        ),
    ]
