# Generated by Django 3.2.13 on 2022-11-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221116_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
