# Generated by Django 3.2.13 on 2022-11-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hits',
            field=models.PositiveIntegerField(default=1, verbose_name='조회수'),
        ),
    ]
