# Generated by Django 3.2.13 on 2022-11-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_search'),
        ('products', '0004_alter_product_like_users'),
    ]

    operations = [
    ]
